# Generated by Django 4.1.5 on 2023-01-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
    ]
